# k8s/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8s-demo-monitor
  namespace: monitoring
  labels:
    release: prometheus   # must match the Helm release name
spec:
  namespaceSelector:
    matchNames:
      - dev
      - prod
  selector:
    matchLabels:
      app: k8s-demo
  endpoints:
    - port: http
      path: /metrics
      interval: 15s